### ISSUE TITLE
ismip6 retreat runs die with invalid memory reference in ESMF timekeeping routines

### ISSUE THREAD

**Issue by trhille** [MALI-Dev/E3SM#71]
This is from the `landice_humboldt_mesh-3km_decomposition_test_velo-none_calving-ismip6_retreat` test case run on Chicoma, but I ran into the same issue with a whole-GIS run on Perlmutter. It seems that some change in timekeeping broke our admittedly fragile logic for using multiple time levels when `config_calving = ismip6_retreat`.

```
Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:
#0  0x1483e8fd6d4f in ???
#1  0x955b7f in __esmf_calendarmod_MOD_isleap
        at /global/cfs/cdirs/fanssie/users/trhille/E3SM/components/mpas-framework/src/external/esmf_time_f90/ESMF_CalendarMod.F90:487
#2  0x95601b in __esmf_calendarmod_MOD_nmonthinyearsec
        at /global/cfs/cdirs/fanssie/users/trhille/E3SM/components/mpas-framework/src/external/esmf_time_f90/ESMF_CalendarMod.F90:392
#3  0x95274b in timegetmonth
        at /global/cfs/cdirs/fanssie/users/trhille/E3SM/components/mpas-framework/src/external/esmf_time_f90/ESMF_TimeMod.F90:1517
#4  0x95479e in __esmf_timemod_MOD_esmf_timeget
        at /global/cfs/cdirs/fanssie/users/trhille/E3SM/components/mpas-framework/src/external/esmf_time_f90/ESMF_TimeMod.F90:478
#5  0x698d2a in __mpas_timekeeping_MOD_mpas_get_time
        at /global/cfs/cdirs/fanssie/users/trhille/E3SM/components/mpas-framework/src/framework/mpas_timekeeping.F:1290
#6  0x5c9536 in ismip6_retreat
        at /global/cfs/cdirs/fanssie/users/trhille/E3SM/components/mpas-albany-landice/src/mode_forward/mpas_li_calving.F:2121
#7  0x5e226a in __li_calving_MOD_li_calve_ice
        at /global/cfs/cdirs/fanssie/users/trhille/E3SM/components/mpas-albany-landice/src/mode_forward/mpas_li_calving.F:274
#8  0x4f6b1e in __li_core_MOD_li_core_initial_solve
        at /global/cfs/cdirs/fanssie/users/trhille/E3SM/components/mpas-albany-landice/src/mode_forward/mpas_li_core.F:794
#9  0x4f726c in __li_core_MOD_li_core_run
        at /global/cfs/cdirs/fanssie/users/trhille/E3SM/components/mpas-albany-landice/src/mode_forward/mpas_li_core.F:415
#10  0x4122fe in __mpas_subdriver_MOD_mpas_run
        at /global/cfs/cdirs/fanssie/users/trhille/E3SM/components/mpas-framework/src/driver/mpas_subdriver.F:358
#11  0x411077 in mpas
        at /global/cfs/cdirs/fanssie/users/trhille/E3SM/components/mpas-framework/src/driver/mpas.F:20
#12  0x4110e2 in main
        at /global/cfs/cdirs/fanssie/users/trhille/E3SM/components/mpas-framework/src/driver/mpas.F:10
srun: error: nid005653: task 0: Segmentation fault
srun: launch/slurm: _step_signal: Terminating StepId=6677099.0

```

**Comment by trhille** [comment]
This commit seems like a possible culprit: 
```
commit a2fc6b90b007e257dcad08438fcfdd312c9af69c
Author: Matthew Hoffman <mhoffman@lanl.gov>
Date:   Fri Apr 29 14:00:36 2022 -0600

    Allow mpas_stream_mgr_read() to read only strictly INPUT direction streams
    
    Previously, the mpas_stream_mgr_read() routine ignored the difference
    between streams of direction INPUT and direction INPUT_OUTPUT (i.e.
    restart streams).  However, there are situation where it would be
    desirable to read only truly direction INPUT streams.  One example is at
    the initial time of a coldstart run - one wants to read any input streams without
    reading the restart stream (which does not exist yet).
    
    This commit adds an optional argument to force mpas_stream_mgr_read to
    ignore INPUT_OUTPUT streams and only read truly INPUT streams.  Its
    default value maintains the previous behavior.
```
